import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { paraglideVitePlugin } from '@inlang/paraglide-js';
import { storybookTest } from '@storybook/addon-vitest/vitest-plugin';
import { sveltekit } from '@sveltejs/kit/vite';
import tailwindcss from '@tailwindcss/vite';
import { playwright } from '@vitest/browser-playwright';
import { coverageConfigDefaults, defineConfig } from 'vitest/config';

const dirname =
    typeof __dirname !== 'undefined'
        ? __dirname
        : path.dirname(fileURLToPath(import.meta.url));

// More info at: https://storybook.js.org/docs/next/writing-tests/integrations/vitest-addon
export default defineConfig(({ mode }) => ({
    plugins: [
        tailwindcss(),
        sveltekit(),
        paraglideVitePlugin({
            project: './project.inlang',
            outdir: './src/lib/paraglide'
        })
    ],
    // Under test only, stop Vite forwarding window `error` events. Vitest has
    // its own unhandled-error path — `onUnhandledError` below, which fails the
    // run on a real one — so Vite's copy is a duplicate that prints a stack for
    // benign browser notifications as well. `npm run dev` keeps the forwarding:
    // there, it is the only thing reporting them.
    server:
        mode === 'test'
            ? { forwardConsole: { unhandledErrors: false } }
            : undefined,
    test: {
        expect: {
            requireAssertions: true
        },
        // "ResizeObserver loop completed with undelivered notifications" is
        // the browser telling itself a layout pass ran long; nothing in src/
        // constructs a ResizeObserver, and it only surfaces when the browser
        // projects run together. @vitest/browser reports it as an *unhandled*
        // error, complete with a stack, so a green run reads like a failing
        // one. Matched on the exact message — a real unhandled error still
        // fails the run.
        //
        // The other known-benign noise, bits-ui's `derived_inert`, is
        // silenced in the browser instead: see
        // `.storybook/silence-known-warnings.ts` for why it cannot be done
        // from here.
        onUnhandledError(error) {
            if (
                typeof error.message === 'string' &&
                error.message.includes('ResizeObserver loop completed')
            ) {
                return false;
            }
        },
        // Count the whole source tree, not just the files a test happened to
        // import. Without `include`, v8 reports on imported modules alone — a
        // module nothing imports is absent from the table rather than showing as
        // 0%, which is exactly the module worth knowing about.
        coverage: {
            include: ['src/**/*.{ts,svelte}'],
            exclude: [
                ...coverageConfigDefaults.exclude,
                'src/lib/paraglide/**', // generated by Paraglide
                'src/stories/**', // Storybook
                'src/tests/**', // the suites themselves
                'src/lib/components/ui/**' // shadcn-copied; not ours to chase
            ]
        },
        projects: [
            {
                extends: './vite.config.ts',
                test: {
                    name: 'client',
                    browser: {
                        enabled: true,
                        provider: playwright(),
                        instances: [
                            {
                                browser: 'chromium',
                                headless: true
                            }
                        ]
                    },
                    // Svelte component tests, plus the markdown converters —
                    // those go through @tiptap/html's browser build and need a
                    // real DOM, which is also exactly how they run in the app.
                    include: [
                        'src/**/*.svelte.{test,spec}.{js,ts}',
                        'src/tests/lib/markdown/**/*.{test,spec}.{js,ts}'
                    ]
                }
            },
            {
                extends: './vite.config.ts',
                test: {
                    name: 'server',
                    environment: 'node',
                    include: ['src/**/*.{test,spec}.{js,ts}'],
                    exclude: [
                        'src/**/*.svelte.{test,spec}.{js,ts}',
                        'src/tests/lib/markdown/**/*.{test,spec}.{js,ts}'
                    ]
                }
            },
            // Every story, run twice — once per theme. The a11y addon is enforcing
            // (`test: 'error'` in .storybook/preview.ts), and axe only ever sees the
            // colours the run happens to render in, so a single project would leave
            // every light-theme contrast defect invisible. The two are identical but
            // for the setup file that pins the theme global.
            ...(['light', 'dark'] as const).map((theme) => ({
                extends: true as const,
                plugins: [
                    // The plugin will run tests for the stories defined in your Storybook config
                    // See options at: https://storybook.js.org/docs/next/writing-tests/integrations/vitest-addon#storybooktest
                    storybookTest({
                        configDir: path.join(dirname, '.storybook')
                    })
                ],
                test: {
                    name: `storybook-${theme}`,
                    setupFiles: [`./.storybook/vitest.setup.${theme}.ts`],
                    browser: {
                        enabled: true,
                        headless: true,
                        provider: playwright({}),
                        instances: [
                            {
                                browser: 'chromium' as const
                            }
                        ]
                    }
                }
            }))
        ]
    }
}));
